### ISSUE TITLE
Objetivos do Produto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#21]
troque os adjetivos por um texto objetivo, ou seja, o que significada cada adjetivo no texto?

"...melhorar **significativamente** a gestão do salão, proporcionando conveniência, **eficiência** e **qualidade**. "

**Comment by vini051** [comment]
Alteramos a estrutura da declaração dos objetivos, removendo os adjetivos visando deixar mais objetivo.
![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/60819460/07a7fb02-df63-434c-bcc8-df7e1bb7538d)
