### ISSUE TITLE
Objetivos do Produto - Secundários

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#22]
Os objetivos secundários **incluem** (EXISTEM OUTROS, ALÉM DOS QUATRO, A SEGUIR?)

1. aumentar a satisfação do cliente, 
2. expandir o negócio, 
3. promover a fidelização de clientes e 
4. destacar o salão de beleza no mercado.

**Vcs tem uma ideia de como vão fazer para verificar se cada um desses objetivos foi atingido?**

**Comment by GuilhermeDSa1013** [comment]
Especificamos os objetivos secundários, os mensurando de uma forma que seja possível verificá-los posteriormente, se foram cumpridos ou não.
![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/92813703/9dfaf793-1453-4164-af73-ecfc3f015939)
