### ISSUE TITLE
Organização do Projeto

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#23]
Vcs estão na disciplina de REQ.
Nenhum dos papéis e atribuições apresentadas pela equipe, refere-se aos papéis e atividades de REQ.

![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/68402547/31f7ea29-e3c5-472e-9304-4286e68f9e35)

**Comment by GuilhermeDSa1013** [comment]
Colocamos as atividades da engenharia de requisitos nos papéis já existentes, não criamos um papel novo para tais atividades.
Tivemos o FeedBack da monitora.
![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/92813703/b036a267-8721-4bc3-85d0-7594ab564426)
