### ISSUE TITLE
Planejamento das Fases/Iterações

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#24]
Períodos variáveis das SPRINTS? INCORRETO.

Coluna de ENTREGA, apresenta atividades, e não, entregas.

SPRINT 9, não apresenta ENTREGAS.

![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/68402547/d275deab-3efd-4433-aad8-12b2d7d0c9f6)

**Comment by vini051** [comment]
Aqui professor, foi corrigido o período das sprints, bem como revisadas as entregas de cada uma.

![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/60819460/f53941db-402f-44a9-bc54-260f60eddc79)
