### ISSUE TITLE
Processo de Desenvolvimento de Software

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#25]
![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/68402547/c5732961-3023-4c3b-95d0-4c99719b33b7)

**Comment by GuilhermeDSa1013** [comment]
Aqui professor, a mudança no Processo:
![SCRAD](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/92813703/dee66373-5104-406c-a61d-53e326df3b01)
