### ISSUE TITLE
USM

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-AngelaCabeleireira#56]
Todo o mapa está, ok. Apenas essa atividade e tarefas que estão em um nível de granularidade muito baixa. Agrupem com outra atividade.

![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/68402547/e7ff5093-9c70-4d09-b21e-a2b111838b41)

**Comment by GuilhermeDSa1013** [comment]
Não consegui agrupar essa atividade com nenhuma outra do Organizador, então subi um pouco mais o nível, considerando que esses detalhes (tipo, data, horário, local) seriam critérios de aceitação de uma US de Criar evento. também adicionei uma outra US de editar os detalhes do evento pois achei necessária. Porém não quis colocar uma de Deletar Evento pois acho que é necessário que os eventos estejam salvos no sistema, mesmo se o evento n ocorra por forças maiores e conste como evento cancelado.
Segue as alterações descritas.
tive o cuidado de renomear a numeração das USs para manter a lógica.
![image](https://github.com/mdsreq-fga-unb/2023.2-AngelaCabeleireira/assets/92813703/8978820b-e4a8-4334-954d-977041123152)
Aguardo retorno para fechar a issue
